### ISSUE TITLE
hamiltonian.return_full_H not working

### ISSUE THREAD

**Issue by calebrich** [JQIamo/pylcp#36]
Calling the function hamiltonian.return_full_H doesn't work and results in this error message like this:
`---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-4-1e311bc6dc3f> in <module>
----> 1 ham.return_full_H(np.array([0,0,0]),np.array([0,0,0]))

~\Anaconda3\envs\laser\lib\site-packages\pylcp\hamiltonian.py in return_full_H(self, Eq, Bq)
    445         for key in self.d_q_bare.keys():
    446             for ii, q in enumerate(np.arange(-1., 2., 1.)):
--> 447                 H -= (0.5*(-1.)**q*self.d_q_bare[key][ii]*Eq[key][2-ii] +
    448                       0.5*(-1.)**q*self.d_q_star[key][ii]*np.conjugate(Eq[key][2-ii]))
    449 

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices`

**Comment by dsbarker** [comment]
I've done a quick check and I can reproduce this error on my `pylcp` installation. The problem appears to be that `Eq` is array-like, not a dictionary, so it shouldn't have a key. I'll push a commit to fix on Github momentarily, but a fix in the PyPi package will have to wait until next week.

**Comment by dsbarker** [comment]
Closed with e2d766528b2b1aa76d4c1ab0317bfc8d44688780.

**Comment by SteveEckel** [comment]
The original code was correct, `Eq` should be a dictionary.  I'm going to roll back Dan's fix.

For a 3-manifold Hamiltonian, you need to specify what transition the electric field is driving.  For a simple two-manifold Hamiltonian, `Eq` should have a single key `g->e`.  If there is more than two manifolds, then you need to make the Eq dictionary with the appropriate keys.

**Comment by SteveEckel** [comment]
Looking at the code, the appropriate fix is to update the documentation so that it is correct :)

**Comment by SteveEckel** [comment]
Rolled back with 7aacd6f18924eec8ef150483ea5b2cfe6dfdea1c.  Updated doc with 6bc5ee61ac4653a106bc52802d4f016b8d860297.  Looking through the code, I see a potential bug where you may not specify all the electric fields in the dictionary that potentially could exist.  Looping through `dq_bare`'s keys will then raise an error.  If the user did not specify all potential keys, we can safely assume those not specified are zero.  Looping instead through `Eq`'s keys will fix that problem.  That's fixed with 70db06617acd9d95154df9346af41385d1bb5284.
